server:
  port: 9191
spring:
  application:
    name: spring-transaction-mgmt
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always # run even for non-embedded DBs like MySQL
      platform: mysql # lets Boot look f  or data-mysql.sql if present
      data-locations:
        - classpath:database/data.sql # explicitly point to your custom path
  docker:
    compose:
      file: spring-transaction-mgmt/compose.yaml # path to your Docker Compose file
      enabled: true # enable Docker Compose support
